<?xml version="1.0" encoding="utf-8"?><Database Name="DataBase" Class="BistroDriveDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DataBase.mdf;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DataBaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_Review" Member="Reviews" ThisKey="Id" OtherKey="Id_Owner" Type="Review" />
      <Association Name="AspNetRole_Review1" Member="Reviews1" ThisKey="Id" OtherKey="Id_User" Type="Review" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
      <Association Name="AspNetRole_ChatMessage" Member="ChatMessages" ThisKey="Id" OtherKey="Id_Reciver" Type="ChatMessage" />
      <Association Name="AspNetRole_ChatMessage1" Member="ChatMessages1" ThisKey="Id" OtherKey="Id_Sender" Type="ChatMessage" />
      <Association Name="AspNetRole_Dish" Member="Dishes" ThisKey="Id" OtherKey="Id_User" Type="Dish" />
      <Association Name="AspNetRole_DishReview" Member="DishReviews" ThisKey="Id" OtherKey="Id_Owner" Type="DishReview" />
      <Association Name="AspNetRole_Order" Member="Orders" ThisKey="Id" OtherKey="Id_Cook" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.Review" Member="Reviews">
    <Type Name="Review">
      <Column Name="Id_UserReview" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_User" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Owner" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Mark" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="AspNetRole_Review" Member="AspNetRole" ThisKey="Id_Owner" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" />
      <Association Name="AspNetRole_Review1" Member="AspNetRole1" ThisKey="Id_User" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="Avatar_Url" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="LastOnlineTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.ChatMessage" Member="ChatMessages">
    <Type Name="ChatMessage">
      <Column Name="Id_Message" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Sender" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Reciver" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="AspNetRole_ChatMessage" Member="AspNetRole" ThisKey="Id_Reciver" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" />
      <Association Name="AspNetRole_ChatMessage1" Member="AspNetRole1" ThisKey="Id_Sender" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dish" Member="Dishes">
    <Type Name="Dish">
      <Column Name="Id_Dish" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_User" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PriceWithIngridient" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Id_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Dish_DishReview" Member="DishReviews" ThisKey="Id_Dish" OtherKey="Id_Dish" Type="DishReview" />
      <Association Name="Dish_OrderProduct" Member="OrderProducts" ThisKey="Id_Dish" OtherKey="Id_Dish" Type="OrderProduct" />
      <Association Name="AspNetRole_Dish" Member="AspNetRole" ThisKey="Id_User" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" />
      <Association Name="DishType_Dish" Member="DishType" ThisKey="Id_Type" OtherKey="Id_DishType" Type="DishType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DishReview" Member="DishReviews">
    <Type Name="DishReview">
      <Column Name="Id_Review" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Owner" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Dish" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Dish_DishReview" Member="Dish" ThisKey="Id_Dish" OtherKey="Id_Dish" Type="Dish" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetRole_DishReview" Member="AspNetRole" ThisKey="Id_Owner" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DishType" Member="DishTypes">
    <Type Name="DishType">
      <Column Name="Id_DishType" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Descritpion" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Image_URL" Type="System.String" DbType="NChar(128)" CanBeNull="true" />
      <Association Name="DishType_Dish" Member="Dishes" ThisKey="Id_DishType" OtherKey="Id_Type" Type="Dish" />
    </Type>
  </Table>
  <Table Name="dbo.[Order]" Member="Orders">
    <Type Name="Order">
      <Column Name="Id_Order" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Cook" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Customer" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FinishTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeadLine" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Id_PaymentMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_ContactMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Delivery" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Order_OrderProduct" Member="OrderProducts" ThisKey="Id_Order" OtherKey="Id_Order" Type="OrderProduct" />
      <Association Name="AspNetRole_Order" Member="AspNetRole" ThisKey="Id_Cook" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="OrderContactMethod_Order" Member="OrderContactMethod" ThisKey="Id_ContactMethod" OtherKey="Id_ContactMethod" Type="OrderContactMethod" IsForeignKey="true" />
      <Association Name="OrderDelivery_Order" Member="OrderDelivery" ThisKey="Id_Delivery" OtherKey="Id_Delivery" Type="OrderDelivery" IsForeignKey="true" />
      <Association Name="OrderPaymentMethod_Order" Member="OrderPaymentMethod" ThisKey="Id_PaymentMethod" OtherKey="Id_PaymentMethod" Type="OrderPaymentMethod" IsForeignKey="true" />
      <Association Name="OrderStatus_Order" Member="OrderStatus" ThisKey="Id_Status" OtherKey="Id_Status" Type="OrderStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderContactMethod" Member="OrderContactMethods">
    <Type Name="OrderContactMethod">
      <Column Name="Id_ContactMethod" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Association Name="OrderContactMethod_Order" Member="Orders" ThisKey="Id_ContactMethod" OtherKey="Id_ContactMethod" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDelivery" Member="OrderDeliveries">
    <Type Name="OrderDelivery">
      <Column Name="Id_Delivery" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Association Name="OrderDelivery_Order" Member="Orders" ThisKey="Id_Delivery" OtherKey="Id_Delivery" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.OrderPaymentMethod" Member="OrderPaymentMethods">
    <Type Name="OrderPaymentMethod">
      <Column Name="Id_PaymentMethod" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Column Name="PaymentProvider" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Association Name="OrderPaymentMethod_Order" Member="Orders" ThisKey="Id_PaymentMethod" OtherKey="Id_PaymentMethod" Type="Order" />
    </Type>
  </Table>
  <Table Name="dbo.OrderProduct" Member="OrderProducts">
    <Type Name="OrderProduct">
      <Column Name="Id_Product" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id_Dish" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Id_Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PriceWithIngridients" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Association Name="Dish_OrderProduct" Member="Dish" ThisKey="Id_Dish" OtherKey="Id_Dish" Type="Dish" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Order_OrderProduct" Member="Order" ThisKey="Id_Order" OtherKey="Id_Order" Type="Order" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderStatus" Member="OrderStatus">
    <Type Name="OrderStatus">
      <Column Name="Id_Status" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(256)" CanBeNull="true" />
      <Association Name="OrderStatus_Order" Member="Orders" ThisKey="Id_Status" OtherKey="Id_Status" Type="Order" />
    </Type>
  </Table>
</Database>