//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BistroDriveWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chatmessage
    {
        public int Id_Message { get; set; }
        public string Id_Sender { get; set; }
        public string Id_Reciver { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    
        public virtual aspnetuser aspnetuser { get; set; }
        public virtual aspnetuser aspnetuser1 { get; set; }
    }
}
