//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BistroDriveWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dish()
        {
            this.DishReviews = new HashSet<DishReview>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int Id_Dish { get; set; }
        public string Id_User { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public decimal PriceWithIngridient { get; set; }
        public string ImageUrl { get; set; }
        public int Id_Type { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual DishType DishType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DishReview> DishReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}
