//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BistroDriveWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int Id_Order { get; set; }
        public string Id_Cook { get; set; }
        public string Id_Customer { get; set; }
        public int Id_Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public System.DateTime DeadLine { get; set; }
        public int Id_PaymentMethod { get; set; }
        public int Id_ContactMethod { get; set; }
        public int Id_Delivery { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual OrderContactMethod OrderContactMethod { get; set; }
        public virtual OrderDelivery OrderDelivery { get; set; }
        public virtual OrderPaymentMethod OrderPaymentMethod { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}
