//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BistroDriveWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderproduct
    {
        public int Id_Product { get; set; }
        public int Id_Dish { get; set; }
        public int Id_Order { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> PriceWithIngridients { get; set; }
    
        public virtual dish dish { get; set; }
        public virtual order order { get; set; }
    }
}
