//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BistroDriveWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.orderproducts = new HashSet<orderproduct>();
        }
    
        public int Id_Order { get; set; }
        public string Id_Cook { get; set; }
        public string Id_Customer { get; set; }
        public int Id_Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public System.DateTime DeadLine { get; set; }
        public int Id_PaymentMethod { get; set; }
        public int Id_ContactMethod { get; set; }
        public int Id_Delivery { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string Address { get; set; }
    
        public virtual aspnetrole aspnetrole { get; set; }
        public virtual ordercontactmethod ordercontactmethod { get; set; }
        public virtual orderdelivery orderdelivery { get; set; }
        public virtual orderpaymentmethod orderpaymentmethod { get; set; }
        public virtual orderstatu orderstatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderproduct> orderproducts { get; set; }
    }
}
