//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BistroDriveWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id_UserReview { get; set; }
        public string Id_User { get; set; }
        public string Id_Owner { get; set; }
        public string Text { get; set; }
        public string Mark { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetRole AspNetRole1 { get; set; }
    }
}
